# HAS TO BE FITTED TO THE USECASE
citizenRequests:
  green-spaces-large-spaces-area:
    en: "*More parks!* We want a large P[park], a W[lake] or a W[river]."
    de: "*Größere Parks!* Wir wollen große P[Parks], W[Seen] oder einen W[Fluss] in unserer Stadt."
    group: zoning
    urgent: false
  green-spaces-count:
    en: "*More parks!* P[parks] and W[water] make the city beautiful and reduce pollution."
    de: "*Mehr Parks!* Mehr P[Parks] und W[Wasserflächen] machen die Stadt schöner und helfen gegen die Luftverschmutzung."
    group: zoning
    urgent: false
  green-spaces-proximity:
    en: "*More parks!* We want P[parks] and W[bodies of water] closer to our homes."
    de: "*Mehr Parks!* Wir wollen P[Parks] und W[Wasserflächen] in der Nähe unserer Häuser."
    group: zoning
    urgent: false
  zone-balance-r-low:
    en: "*More R[residential zones]!* We need homes to live in."
    de: "*Mehr R[Wohngebiete]!* Wir brauchen mehr Häuser, in denen wir leben können."
    group: zoning
    urgent: true
  zone-balance-e-low:
    en: "*More S[energy]!* We need more energy to produce."
    de: "*Mehr S[Energie]!* Wir brauchen mehr Windenergie."
    group: zoning
    urgent: true
  zone-balance-r-high:
    en: "*Less R[residential zones]!* Many houses are empty."
    de: "*Weniger R[Wohngebiete]!* Viele Häuser stehen leer."
    group: zoning
    urgent: false
  zone-balance-e-high:
    en: "*Less S[energy]!* A lot of energy is unused and wind turbines destroy the landscape."
    de: "*Weniger S[Energie]!* Viel Energie bleibt ungenutzt und die Anlagen zerstören das Landschaftsbild."
    group: zoning
    urgent: false
  wind-turbine-distance-low:
    en: "*Increase spacing!* There is not enough spacing around the wind turbines."
    de: "*Vergrößere den Abstand!* Der Abstand um die Windenergieanlagen herum ist nicht groß genug."
    group: distance
    urgent: true
citizenIcons:
  regular:
    - static/openmoji/bw/man-beard.svg
    - static/openmoji/bw/man-older.svg
    - static/openmoji/bw/man-raising-hand.svg
    - static/openmoji/bw/man.svg
    - static/openmoji/bw/person-bald.svg
    - static/openmoji/bw/person.svg
    - static/openmoji/bw/person-raising-hand.svg
    - static/openmoji/bw/person-older.svg
    - static/openmoji/bw/person-curly.svg
    - static/openmoji/bw/woman-older.svg
    - static/openmoji/bw/woman-raising-hand.svg
    - static/openmoji/bw/woman.svg
    - static/openmoji/bw/woman-curly.svg
    - static/openmoji/bw/woman-headscarf.svg
  urgent:
    - static/openmoji/bw/person-frowning.svg
    - static/openmoji/bw/woman-frowning.svg
    - static/openmoji/bw/man-frowning.svg
