goals:
  green-spaces:
    # Number of green spaces a city should have (at least)
    num: 50
    # Minimum number of tiles a green space needs to have to qualify as "large"
    large-spaces-threshold: 3
    # Total area of large green spaces a city should have (at least)
    large-spaces-area: 16
    # Distance (in tiles) a park needs to be from a residential area to qualify as "medium" proximity.
    proximity-med: 5
    # Distance (in tiles) a park needs to be from a residential area to qualify as "near" proximity.
    proximity-near: 3
    # Percentage of residential areas that need to be closer than the threshold (as fraction, 1 = 100%).
    proximity-goal-percentage: 0.75
  distances:
    # Distance between small wind turbines and water and road has to be at least 1 tile
    windTurbineSmall-distance-water-roads: 1
    # Distance between small wind turbines and residential area has to be at least 2 tile
    windTurbineSmall-distance-residentials: 2
    # Distance between big wind turbines and water and road has to be at least 2 tile
    windTurbineBig-distance-water-roads: 2
    # Distance between big wind turbines and residential area has to be at least 3 tile
    windTurbineBig-distance-residentials: 3
  zone-balance:
    # Percentage of zoned areas that should (ideally) be residential
    ideal-residential-percentage: 0.3
    # Percentage of zoned areas that should (ideally) be residential
    ideal-windTurbine-percentage: 0.25
    # Minimum percentage of tiles that should be zoned areas
    underdeveloped-percentage: 0.35
    # Maximum percentage of tiles that should be zoned areas
    overdeveloped-percentage: 0.47
    # Difference from the ideal percentage that is acceptable (as fraction, 1 = 100%).
    acceptable-percentage-difference: 0.25
